export type QuizQuestion = {
  q: string;
  choices: string[];
  answer: number; // index in choices
  explain?: string;
};

// Soft end-of-module quizzes. 3 questions each, plain-language for older traders.
export const QUIZZES: Record<number, QuizQuestion[]> = {
  1: [
    { q: "A candle shows four prices. Which is NOT one of them?",
      choices: ["Open", "High", "Volume", "Close"], answer: 2,
      explain: "Volume is shown separately, not inside the candle." },
    { q: "A green (bullish) candle means:",
      choices: ["Close is below open", "Close is above open", "The wick is longer than the body", "Nothing, colors are random"],
      answer: 1 },
    { q: "The 'wick' of a candle represents:",
      choices: ["Trading fees", "Price the market rejected", "Only the open price", "The next day's forecast"],
      answer: 1, explain: "Wicks show highs and lows the market pushed to but did not close at." },
  ],
  2: [
    { q: "Support is a price level where:",
      choices: ["Buyers tend to step in", "Sellers overwhelm the market", "The chart resets", "Fees are highest"], answer: 0 },
    { q: "Resistance becoming support after a breakout is called a:",
      choices: ["Rejection", "Flip / retest", "Stop hunt", "Doji"], answer: 1 },
    { q: "Equal highs on a chart often signal:",
      choices: ["Nothing meaningful", "Liquidity resting above", "A guaranteed reversal", "That volume is broken"], answer: 1 },
  ],
  3: [
    { q: "An uptrend is defined by:",
      choices: ["Lower highs, lower lows", "Higher highs, higher lows", "Equal highs and lows", "No structure at all"], answer: 1 },
    { q: "A range is best traded by:",
      choices: ["Buying the top", "Selling the bottom", "Buying support, selling resistance", "Ignoring the levels"], answer: 2 },
    { q: "A break of structure (BOS) means:",
      choices: ["Price broke a prior swing point", "The exchange went down", "Volume disappeared", "News was released"], answer: 0 },
  ],
  4: [
    { q: "A clean setup usually has:",
      choices: ["Multiple confluences and a clear invalidation", "Random entries", "No stop loss", "Only a gut feeling"], answer: 0 },
    { q: "The best R:R (reward-to-risk) for beginners is typically:",
      choices: ["0.5:1 or less", "At least 1.5:1 to 2:1", "10:1 always", "R:R doesn't matter"], answer: 1 },
    { q: "Confluence means:",
      choices: ["One indicator screaming buy", "Multiple signals pointing the same way", "A news event", "A random signal"], answer: 1 },
  ],
  5: [
    { q: "Risking 1% per trade on a $10,000 account means max loss of:",
      choices: ["$1", "$10", "$100", "$1,000"], answer: 2 },
    { q: "Position size should be calculated from:",
      choices: ["Your feelings", "Stop distance and dollar risk", "The candle color", "Time of day"], answer: 1 },
    { q: "A stop loss should be placed:",
      choices: ["Where your idea is invalid", "As close as possible", "Never", "At a round number only"], answer: 0 },
  ],
  6: [
    { q: "A liquidity sweep is when price:",
      choices: ["Grabs stops beyond a level then reverses", "Moves sideways slowly", "Closes at the open", "Prints a doji"], answer: 0 },
    { q: "Equal lows often act as:",
      choices: ["A magnet for stop-hunting", "Guaranteed support forever", "News events", "Nothing"], answer: 0 },
    { q: "Order blocks are:",
      choices: ["Zones of large orders that moved price", "Chart drawing tools", "News alerts", "Types of candles"], answer: 0 },
  ],
  7: [
    { q: "Higher-timeframe bias should:",
      choices: ["Be ignored on lower timeframes", "Guide lower-timeframe entries", "Only matter on Mondays", "Contradict entries"], answer: 1 },
    { q: "Top-down analysis starts on:",
      choices: ["The 1-minute chart", "The highest relevant timeframe", "Any random timeframe", "Only tick charts"], answer: 1 },
    { q: "The 15m entry works best when:",
      choices: ["It contradicts the 4h", "It aligns with 4h trend and 1h structure", "There is no bias", "The market is closed"], answer: 1 },
  ],
  8: [
    { q: "The London session overlaps with:",
      choices: ["Only Sydney", "New York for a few hours", "Never overlaps", "Only Tokyo"], answer: 1 },
    { q: "Highest volatility typically occurs during:",
      choices: ["Asian midnight", "London/NY overlap", "Weekends", "Holidays"], answer: 1 },
    { q: "VWAP stands for:",
      choices: ["Volume Weighted Average Price", "Very Wide Average Point", "Volatility Weighted Auto Price", "Vertical Wave Analysis Pattern"], answer: 0 },
  ],
  9: [
    { q: "A trading journal should record:",
      choices: ["Only wins", "Entry, exit, reason, and outcome", "Nothing", "Only losses"], answer: 1 },
    { q: "Your mental state matters because:",
      choices: ["It affects execution and discipline", "It doesn't", "Only pros track it", "It changes prices"], answer: 0 },
    { q: "Reviewing past trades helps you:",
      choices: ["Spot repeating mistakes", "Guarantee future wins", "Skip risk management", "Predict the market"], answer: 0 },
  ],
  10: [
    { q: "Paper trading is useful for:",
      choices: ["Testing without risk", "Guaranteeing profits", "Skipping learning", "Nothing"], answer: 0 },
    { q: "A kill-switch on drawdown protects you by:",
      choices: ["Closing everything if losses exceed a limit", "Adding to losers", "Doubling risk", "Randomizing size"], answer: 0 },
    { q: "Backtesting means:",
      choices: ["Reviewing how a strategy would have performed on historical data", "Guessing the future", "A prop-firm rule", "A candle pattern"], answer: 0 },
  ],
  11: [
    { q: "Overtrading is often caused by:",
      choices: ["Boredom or revenge after a loss", "A good plan", "Waiting for setups", "Journaling"], answer: 0 },
    { q: "Discipline in trading means:",
      choices: ["Following your plan even when it's uncomfortable", "Ignoring the plan", "Only trading news", "Trading every candle"], answer: 0 },
    { q: "FOMO (fear of missing out) leads to:",
      choices: ["Chasing bad entries", "Better setups", "Higher R:R", "Nothing"], answer: 0 },
  ],
  12: [
    { q: "A trading plan should include:",
      choices: ["Entry rules, risk, and invalidation", "Only entries", "Just a gut feeling", "News tips"], answer: 0 },
    { q: "Consistency comes from:",
      choices: ["Repeating an edge with discipline", "Random trades", "Changing strategies daily", "Ignoring risk"], answer: 0 },
    { q: "Long-term traders focus on:",
      choices: ["Process and risk over any single trade", "Only wins", "Only losses", "Copying others blindly"], answer: 0 },
  ],
};

export function getQuiz(moduleId: number): QuizQuestion[] | null {
  return QUIZZES[moduleId] ?? null;
}

// One question per lesson, matched to that lesson's content. Keyed by lesson id.
export const LESSON_CHECKS: Record<string, QuizQuestion> = {
  // Module 1 — Chart Foundations
  "1.1": { q: "Trading, in one sentence, is:",
    choices: ["Buying and selling something to profit from price changes", "Guessing lottery numbers", "Only for banks", "Reading the news"],
    answer: 0, explain: "A trade is simply buying low and selling high (or the reverse) on a price chart." },
  "1.2": { q: "On a price chart, time runs:",
    choices: ["Top to bottom", "Right to left", "Left to right", "In a circle"],
    answer: 2, explain: "The oldest price is on the left, the newest on the right." },
  "1.3": { q: "A single candlestick shows you:",
    choices: ["Only the closing price", "Open, high, low, and close for one period", "Tomorrow's price", "The trader's profit"],
    answer: 1 },
  "1.4": { q: "A higher timeframe (like the daily) is best used for:",
    choices: ["Exact entry timing", "The big-picture direction", "Counting volume", "Setting alerts"],
    answer: 1, explain: "Higher timeframes show the trend; lower timeframes show the detail." },
  "1.5": { q: "At any moment, price is doing one of three things:",
    choices: ["Up, down, or flat (trending, ranging, reversing)", "Only going up", "Following the news", "Copying yesterday"],
    answer: 0 },
  "1.6": { q: "Support is a level where price has:",
    choices: ["Always reversed forever", "Reacted before and may react again", "Never been", "The highest volume ever"],
    answer: 1 },
  "1.7": { q: "A swing high is:",
    choices: ["The highest price ever", "A pivot point where price turned down", "The day's open", "A type of candle"],
    answer: 1, explain: "Swing points are the pivots you use to read structure." },
  "1.8": { q: "Rising volume on a move suggests:",
    choices: ["The move has conviction behind it", "The move is fake", "Nothing", "The market is closed"],
    answer: 0 },

  // Module 2 — Price Behavior + BBHG
  "2.1": { q: "A retest is when price:",
    choices: ["Returns to a level it broke before continuing", "Gaps over the weekend", "Closes at the open", "Doubles in one candle"],
    answer: 0 },
  "2.2": { q: "After a pause in a trend, the most likely outcome is:",
    choices: ["A full reversal", "Continuation of the trend", "The market closes", "A news event"],
    answer: 1, explain: "Continuation is the norm, not the exception." },
  "2.3": { q: "A long wick at a level tells you:",
    choices: ["Price refused to go there", "Volume was high", "The trend is over", "Nothing useful"],
    answer: 0 },
  "2.4": { q: "A real break is best confirmed by:",
    choices: ["A wick poking through", "A candle closing beyond the level", "A rumor", "A big spread"],
    answer: 1, explain: "Closes matter more than wicks." },
  "2.5": { q: "BBHG stands for:",
    choices: ["Buy, Borrow, Hold, Gain", "Break, Breathe, Hold, Go", "Break, Buy, Hedge, Go", "Bounce, Break, Halt, Go"],
    answer: 1 },
  "2.6": { q: "A strong, fast reaction at a level usually means:",
    choices: ["Nobody cares about the level", "Buyers or sellers are defending it", "The level is broken", "The chart is wrong"],
    answer: 1 },
  "2.7": { q: "A momentum shift often appears:",
    choices: ["Only after the reversal is complete", "Before price fully reverses", "Only on Mondays", "Never"],
    answer: 1 },
  "2.8": { q: "Reading price behavior means combining:",
    choices: ["Structure, level, and reaction", "News and feelings", "Random indicators", "Time of day only"],
    answer: 0 },

  // Module 3 — Decision-Making + Execution
  "3.1": { q: "A good entry is:",
    choices: ["A reflex when price moves", "A planned decision with a reason", "Always at the open", "Whatever feels right"],
    answer: 1 },
  "3.2": { q: "Exits should be planned:",
    choices: ["After the trade is in profit", "Before you enter", "Never", "Only for losers"],
    answer: 1 },
  "3.3": { q: "Invalidation is:",
    choices: ["The price that proves your setup is broken", "A broker fee", "A news event", "Your profit target"],
    answer: 0 },
  "3.4": { q: "You should only take trades where:",
    choices: ["Risk outweighs reward", "Reward outweighs risk", "The spread is wide", "You feel lucky"],
    answer: 1 },
  "3.5": { q: "The best trade is often:",
    choices: ["The biggest one", "No trade at all", "The fastest one", "The one with leverage"],
    answer: 1 },

  // Module 4 — Guided Review + Practice
  "4.1": { q: "Before anything else on a chart, you should name:",
    choices: ["The exact target", "Whether price is trending, ranging, or reversing", "The broker's spread", "The news schedule"],
    answer: 1 },
  "4.2": { q: "In BBHG, 'Breathe' means:",
    choices: ["Price pulls back after the break", "You stop trading", "The market closes", "Volume disappears"],
    answer: 0 },
  "4.3": { q: "A messy setup is best handled by:",
    choices: ["Trading it bigger", "Walking away", "Doubling the stop", "Ignoring it halfway"],
    answer: 1 },
  "4.4": { q: "The last touch of a level tells you:",
    choices: ["Nothing", "How price behaved and who was in control", "The exact future", "The spread"],
    answer: 1 },
  "4.5": { q: "A stop loss belongs:",
    choices: ["As tight as possible", "Beyond the point where the idea is wrong", "At a round number", "Anywhere"],
    answer: 1 },
  "4.6": { q: "A profit target belongs at:",
    choices: ["A random number", "The next meaningful level", "Double your entry", "The day's high always"],
    answer: 1 },
  "4.7": { q: "If you cannot explain a trade in one sentence, you should:",
    choices: ["Take it anyway", "Not take it", "Increase the size", "Ask a friend to take it"],
    answer: 1 },

  // Module 5 — Liquidity + Intent
  "5.1": { q: "Liquidity is:",
    choices: ["Where clusters of orders sit", "How fast your internet is", "The spread", "A candle pattern"],
    answer: 0 },
  "5.2": { q: "Equal highs tend to attract price because:",
    choices: ["They look nice", "Stop orders stack just above them", "They are round numbers", "Of the news"],
    answer: 1 },
  "5.3": { q: "A stop hunt is:",
    choices: ["A fast poke through a level to trigger stops", "A broker error", "A long trend", "A holiday gap"],
    answer: 0 },
  "5.4": { q: "A liquidity sweep usually happens:",
    choices: ["After the real move ends", "Just before the real move begins", "Only on weekends", "Randomly with no meaning"],
    answer: 1 },
  "5.5": { q: "An order block is:",
    choices: ["The last opposite candle before a strong move", "A trading halt", "A type of broker order", "A news alert"],
    answer: 0 },
  "5.6": { q: "Fast moves often leave imbalances that price tends to:",
    choices: ["Ignore forever", "Come back and fill", "Delete from the chart", "Double"],
    answer: 1 },
  "5.7": { q: "Reading intent means asking:",
    choices: ["Is price building at a level or breaking through?", "What is the spread?", "What time is it?", "Who else is trading?"],
    answer: 0 },
  "5.8": { q: "Displacement refers to:",
    choices: ["Big, forceful candles that shift the balance", "Slow sideways drift", "A gap at the open only", "Low volume"],
    answer: 0 },

  // Module 6 — Clean Setups + Confluence
  "6.1": { q: "A clean setup needs:",
    choices: ["Level, reaction, and invalidation", "Just a feeling", "Only an indicator", "A big account"],
    answer: 0 },
  "6.2": { q: "Messy setups should be:",
    choices: ["Traded smaller", "Skipped", "Traded faster", "Averaged into"],
    answer: 1 },
  "6.3": { q: "The two ingredients that must be present are:",
    choices: ["News and volume", "Level and reaction", "Spread and leverage", "Time and luck"],
    answer: 1 },
  "6.4": { q: "Confluence means:",
    choices: ["One strong signal", "Multiple reasons stacking in one spot", "A fast move", "A wide stop"],
    answer: 1 },
  "6.5": { q: "When timeframes disagree:",
    choices: ["The lower timeframe wins", "The higher timeframe wins", "Flip a coin", "Trade both ways"],
    answer: 1 },
  "6.6": { q: "Session timing matters because:",
    choices: ["Some hours have far more movement and volume", "Charts look nicer at noon", "Brokers close early", "It does not matter"],
    answer: 0 },
  "6.7": { q: "Scheduled news events can:",
    choices: ["Be ignored", "Break structure instantly, so know when they are", "Only help trades", "Only matter for stocks"],
    answer: 1 },
  "6.8": { q: "Grading a setup before trading helps you:",
    choices: ["Trade everything equally", "Save your best risk for the best setups", "Avoid journaling", "Skip stops"],
    answer: 1 },

  // Module 7 — Risk + Trade Management
  "7.1": { q: "A sensible risk per trade is:",
    choices: ["Half the account", "A small percent like 1-2%", "Whatever feels right", "Everything on A+ setups"],
    answer: 1 },
  "7.2": { q: "Stops go:",
    choices: ["Just inside the level", "Beyond the invalidation level", "At breakeven always", "Wherever the broker suggests"],
    answer: 1 },
  "7.3": { q: "Targets belong at:",
    choices: ["The next meaningful level", "A random round number", "Double the stop always", "The previous close"],
    answer: 0 },
  "7.4": { q: "Position size is calculated from:",
    choices: ["Your mood", "Stop distance and your dollar risk", "Account balance alone", "The candle color"],
    answer: 1 },
  "7.5": { q: "Moving a stop to breakeven makes sense:",
    choices: ["Immediately at entry", "Once the trade has worked in your favor", "Never", "Only on losses"],
    answer: 1 },
  "7.6": { q: "Scaling out means:",
    choices: ["Adding to losers", "Taking partial profit to lock in results", "Closing everything at once", "Doubling size"],
    answer: 1 },
  "7.7": { q: "The best traders lose:",
    choices: ["Never", "Big", "Small and fast", "Only on Fridays"],
    answer: 2 },
  "7.8": { q: "Every trade should go in the journal because:",
    choices: ["It is fun", "Reviewing it is how you improve", "Brokers require it", "It changes the outcome"],
    answer: 1 },

  // Module 8 — Mindset + Discipline
  "8.1": { q: "The trade you do not take is often:",
    choices: ["A mistake", "The win", "A loss", "Illegal"],
    answer: 1 },
  "8.2": { q: "Chasing means:",
    choices: ["Entering after the move is already gone", "Waiting patiently", "Using a stop", "Trading the open"],
    answer: 0 },
  "8.3": { q: "The right response to FOMO is to:",
    choices: ["Enter immediately", "Recognize it and pass", "Double the size", "Switch markets"],
    answer: 1 },
  "8.4": { q: "After a frustrating loss, the best move is to:",
    choices: ["Win it back right away", "Step away and close the platform", "Increase leverage", "Blame the broker"],
    answer: 1 },
  "8.5": { q: "Overtrading usually comes from:",
    choices: ["A solid plan", "Boredom or the urge to always be in a trade", "Good risk management", "Journaling"],
    answer: 1 },
  "8.6": { q: "The only thing you fully control in trading is:",
    choices: ["The market", "Your plan and whether you follow it", "The news", "Other traders"],
    answer: 1 },
  "8.7": { q: "Losses are:",
    choices: ["Proof you are a bad trader", "The normal cost of doing business", "Avoidable entirely", "A reason to quit"],
    answer: 1 },
  "8.8": { q: "After a big win you should:",
    choices: ["Double your size immediately", "Stay humble and keep following the plan", "Stop journaling", "Take the week off celebrating"],
    answer: 1 },

  // Module 9 — Real Chart Story Reading
  "9.1": { q: "Every chart tells:",
    choices: ["Only the present", "A beginning, middle, and end", "Nothing useful", "Only the future"],
    answer: 1 },
  "9.2": { q: "To understand a move, first find:",
    choices: ["The current candle", "Where the move started", "The spread", "The loudest opinion online"],
    answer: 1 },
  "9.3": { q: "You should be able to name the current phase in:",
    choices: ["A full essay", "One sentence", "A spreadsheet", "No words"],
    answer: 1 },
  "9.4": { q: "The next likely destination for price is:",
    choices: ["Random", "The next real level", "Yesterday's close", "The round number"],
    answer: 1 },
  "9.5": { q: "Big candles versus small candles tell you about:",
    choices: ["The broker", "Momentum", "The time zone", "Nothing"],
    answer: 1 },
  "9.6": { q: "Rejection wicks show:",
    choices: ["What price refused to do", "The exact top", "Low volume", "A data error"],
    answer: 0 },
  "9.7": { q: "A shift in volume can tell you:",
    choices: ["The story is changing", "Nothing", "The market closed", "The chart is broken"],
    answer: 0 },
  "9.8": { q: "The best test of understanding a chart is:",
    choices: ["Trading it big", "Being able to explain it to someone else", "Screenshotting it", "Memorizing the price"],
    answer: 1 },

  // Module 10 — Execution Lab
  "10.1": { q: "The pre-trade checklist exists so that:",
    choices: ["You never click without ticking every box", "You trade faster", "You skip planning", "You impress others"],
    answer: 0 },
  "10.2": { q: "Before looking for entries, decide:",
    choices: ["Your position size", "Your directional bias", "Your broker", "Your target"],
    answer: 1 },
  "10.3": { q: "The level should be marked:",
    choices: ["After you enter", "Before you look for the entry", "Never", "Only on Fridays"],
    answer: 1 },
  "10.4": { q: "At a level you should:",
    choices: ["Enter immediately", "Wait for the reaction", "Double your size", "Look away"],
    answer: 1 },
  "10.5": { q: "You should be able to explain:",
    choices: ["Nothing, just click", "The trigger for your entry", "Only the target", "The broker's fees"],
    answer: 1 },
  "10.6": { q: "While in a trade, exits should be decided by:",
    choices: ["Emotions", "Structure", "Hope", "The clock"],
    answer: 1 },
  "10.7": { q: "Take profit at:",
    choices: ["A random number", "The next real level", "Exactly 10 pips always", "The end of the day always"],
    answer: 1 },
  "10.8": { q: "Which trades go into the journal?",
    choices: ["Only winners", "Only losers", "Every single one", "Only big ones"],
    answer: 2 },

  // Module 11 — Practice
  "11.1": { q: "Spotting setups on historical charts builds:",
    choices: ["Nothing", "Pattern recognition without risking money", "Overconfidence", "Speed only"],
    answer: 1 },
  "11.2": { q: "Before looking at what happened next, you should:",
    choices: ["Scroll ahead", "Name the phase", "Check the news", "Guess the outcome"],
    answer: 1 },
  "11.3": { q: "Classifying every setup as clean or messy trains you to:",
    choices: ["Trade more", "Skip the bad ones", "Ignore risk", "Trade faster"],
    answer: 1 },
  "11.4": { q: "Drawing entry, stop, and target on the chart forces you to:",
    choices: ["Decorate the chart", "Define the full trade before taking it", "Impress friends", "Avoid journaling"],
    answer: 1 },
  "11.5": { q: "Comparing your read to the platform's scan helps you:",
    choices: ["Copy blindly", "Calibrate your own judgment", "Skip learning", "Avoid practice"],
    answer: 1 },
  "11.6": { q: "Paper trading a setup means:",
    choices: ["Risking real money", "Practicing the trade with no real money at risk", "Reading about trading", "Watching others"],
    answer: 1 },
  "11.7": { q: "Practice trades should be logged:",
    choices: ["Never, they are not real", "Like real trades, every one", "Only if they win", "Once a month"],
    answer: 1 },
  "11.8": { q: "Skill in trading is built through:",
    choices: ["One big win", "Repetition until it is automatic", "Luck", "More indicators"],
    answer: 1 },

  // Module 12 — Review + Framework
  "12.1": { q: "Candles, timeframes, and structure should now be:",
    choices: ["Confusing", "Second nature", "Optional", "Ignored"],
    answer: 1 },
  "12.2": { q: "Price behavior at levels should be read using:",
    choices: ["Guesses", "BBHG, every time", "News only", "Random indicators"],
    answer: 1 },
  "12.3": { q: "The four BBHG phases are:",
    choices: ["Buy, Borrow, Hold, Gain", "Break, Breathe, Hold, Go", "Bounce, Break, Halt, Go", "Build, Break, Hold, Grow"],
    answer: 1 },
  "12.4": { q: "Price tends to move toward:",
    choices: ["Round numbers only", "Where the stops and orders sit", "The previous close", "Random places"],
    answer: 1 },
  "12.5": { q: "Your risk per trade should be:",
    choices: ["1 to 2 percent, always", "Whatever feels right", "Half the account", "Zero, never risk anything"],
    answer: 0 },
  "12.6": { q: "The mindset to repeat is:",
    choices: ["Fast, greedy, bold", "Calm, patient, humble", "Angry, quick, stubborn", "Fearful, hesitant, late"],
    answer: 1 },
  "12.7": { q: "Your trading plan should fit on:",
    choices: ["A hundred pages", "One page", "A napkin of feelings", "Nothing, plans are optional"],
    answer: 1 },
  "12.8": { q: "The long-term formula is:",
    choices: ["One lucky trade", "Practice, journal, repeat, forever", "More leverage", "Copying others"],
    answer: 1 },
};

export function getLessonCheck(lessonId: string): QuizQuestion | null {
  return LESSON_CHECKS[lessonId] ?? null;
}
